# Generated by Django 2.1.7 on 2019-06-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='ban_img',
            field=models.ImageField(blank=True, null=True, upload_to='banners/images'),
        ),
    ]
