# Generated by Django 2.1.7 on 2019-06-10 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_category_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date_news',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
