# Generated by Django 2.1.7 on 2019-06-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20190610_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
