# Generated by Django 2.2.2 on 2019-06-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_field',
            field=models.SlugField(blank=True),
        ),
    ]
