# Generated by Django 2.2.2 on 2019-06-13 06:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBlog', '0003_auto_20190612_1214'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
