# Generated by Django 2.2.2 on 2019-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0005_auto_20190612_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_field',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
