# Generated by Django 2.2.2 on 2019-06-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0007_category_available_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='available_sale',
            new_name='available',
        ),
    ]
