# Generated by Django 2.2.2 on 2019-06-13 06:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0008_auto_20190612_1817'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brand',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
    ]
