# Generated by Django 2.2.2 on 2019-06-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0010_auto_20190613_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofsaleproduct',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
